services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: npm install
    startCommand: npm start  # This will use the "start" script in package.json
    envVars:
      - key: MONGODB_URI
        fromDatabase: MONGODB_URI
      - key: JWT_SECRET
        fromDatabase: JWT_SECRET
      - key: GIPHY_API_KEY
        fromDatabase: GIPHY_API_KEY
      - key: CLIENT_URL
        fromDatabase: CLIENT_URL
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
