services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-atlas-uri
      - key: JWT_SECRET
        generateValue: true
      - key: GIPHY_API_KEY
        value: your-giphy-api-key